name = "Blockupelago"
home = "https://discord.com/channels/731205301247803413/1461589714661543958"
default_url = "https://github.com/StefanDucharme/blockupelago/releases/download/v{{version}}/blockupelago.apworld"

[versions]
"2.2.0" = { url = "https://github.com/StefanDucharme/blockupelago/releases/download/v2.2/blockupelago.apworld" }
