name = "Bloons TD6"
home = "https://github.com/Matt41321/Archipelago/releases"
default_url = "https://github.com/Matt41321/Archipelago/releases/download/v0.7.1/bloonstd6.apworld"

[versions]
"0.7.1" = {}
