name = "Black Ops 3 - Zombies"
home = "https://discord.com/channels/1085716850370957462/1205200487175950386"
tags = ["ad"]
default_url = "https://github.com/colin969/bo3_archipelago/releases/download/{{version}}/cod_bo3.apworld"

[versions]
"0.5.1" = {}
"0.4.0" = {}
"0.3.0" = {}
"0.2.3" = {}
"0.4.1" = {}
"0.5.4" = {}
"0.5.7" = {}
"0.5.8" = {}