name = "Crash Team Racing"
home = "https://discord.com/channels/731205301247803413/1222304293751750777"
default_url = "https://github.com/dowlle/ctr-native-ap/releases/download/v{{version}}/ctr.apworld"

[versions]
"0.2.1-alpha2" = {}
"0.2.1" = {}
