name = "DREDGE"
home = "https://discord.com/channels/731205301247803413/1323663496566542336"

[versions]
"0.5.1" = { url = "https://github.com/alextric234/ArchipelagoDredge/releases/download/dredge_0.5.1/dredge.apworld" }
