name = "Manual_DonkeyKongBananzaopenworld_Konijnde"
display_name = "Manual: Donkey Kong Bananza"
home = "https://github.com/Konijnde/DKBManualAP"

[versions]
"0.1.0" = {url = "https://github.com/Konijnde/DKBManualAP/releases/download/apworld/manual_donkeykongbananzaopenworld_konijnde.apworld"}
