name = "Manual_SuperMarioBrosMovie_ZiskaTheSilly"
display_name = "Manual: Super Mario Bros. Movie (2023)"

[versions]
"1.0.0" = { url = "https://github.com/ZiTheSilly/Super-Mario-Bros-Movie-Manual/releases/download/v1.0.0/manual_supermariobrosmovie_ziskathesilly.apworld"}
