name = "Majora's Mask Recompiled"
home = "https://discord.com/channels/731205301247803413/1368653154241089546"

[versions]
"0.9.5a" = { url = "https://github.com/RecompRando/MMRecompRando/releases/download/v0.9.5a/mm_recomp.apworld" }
