name = "Mega Man X4"
home = "https://discord.com/channels/731205301247803413/1365560558224674826"
default_url = "https://github.com/Daxtear/ArchipelagoMMX4/releases/download/{{version}}/mmx4.apworld"

[versions]
"0.0.6" = {}
"0.1.0" = {}
"0.1.2" = {}
"0.1.3" = {}