name = "NEO: The World Ends with You"
home = "https://discord.com/channels/731205301247803413/1297080429387579402"
default_url = "https://github.com/Sjerver/NEO-Twewy-Archipelago-Mod/releases/download/v.{{version}}/neotwewy.apworld"

[versions]
"0.0.4" = {}
