name = "Ori and the Will of the Wisps"
display_name = "Ori and the Will of the Wisps"
default_url = "https://github.com/Satisha10/APwotw_release/releases/download/v{{versions}}/ori_wotw.apworld"

[version]
"0.6.4" ={}