name = "Shovel Knight: Pocket Dungeon"
home = "https://discord.com/channels/731205301247803413/1447983047185141830"
default_url = "https://github.com/Mitchell1711/Archipelago/releases/download/v{{version}}/pocket_dungeon.apworld"

[versions]
"0.3.2" = {}
