name = "Pokemon Black and White"
home = "https://discord.com/channels/731205301247803413/1414928022854696991"
default_url = "https://github.com/BlastSlimey/PokemonBWAP/releases/download/{{version}}/pokemon_bw.apworld"
# Old versions: Has code that steals items with "badge", "tm" or "hm" and
# places them with no logic in its own world and are inflated size

[versions]
# "0.3.17" = {}
# "0.3.14" = {}
# "0.3.13" = {}
"0.3.30" = {}
