name = "Ratchet & Clank: Size Matters"
home = "https://discord.com/channels/731205301247803413/1501230470543839372"
default_url = "https://github.com/Panguu/Archipelago-RaCSM/releases/download/rac_size_matters-v{{version}}/rac_size_matters.apworld"

[versions]
"0.5.1" = {}
"0.5.3" = {}
