name = "The Simpsons Hit And Run"
home = "https://discord.com/channels/731205301247803413/1158211913495359548"

[versions]
"0.5.4-alpha" = { url = "https://github.com/nmize1/Archipelago/releases/download/v0.5.4b/simpsonshitnrun.apworld" }
