name = "Super Mario Odyssey"

home = "https://discord.com/channels/1345801058609270794/1537330671314411541"

default_url = "https://github.com/AdalynBlack/SuperMarioOdysseyArchipelago/releases/tag/v1.7.6-1"

[versions]
"1.7.6-1" = {}
