name = "Tetris"
home = "https://discord.com/channels/731205301247803413/1212629606608408576"
default_url = "https://github.com/Alchav/Archipelago/releases/download/tetris-{{version}}/tetris_gb.apworld"

[versions]
"0.2.1" = {}