name = "The Legend of Zelda - Phantom Hourglass"
home = "https://discord.com/channels/731205301247803413/1545411847593787472"
default_url = "https://github.com/carrotinator/Archipelago/releases/download/ph-v{{version}}/tloz_ph.apworld"

[versions]
"0.10.0-alpha" = {}
