name = "The Legend of Zelda - Oracle of Ages"
home = "https://discord.com/channels/731205301247803413/1492540520462024774"
default_url = "https://github.com/josephanimate2021/ArchipelagoOoA/releases/download/v{{version}}/tloz_ooa.apworld"

[versions]
"0.4.3+hotfix-0.6.2" = { local = "../apworlds/tloz_ooa-0.4.3+hotfix-0.6.2.apworld" }
"0.5.1" = { }
"1.1.2" = { }
