name = "Undertale Yellow"
home = "https://discord.com/channels/731205301247803413/1538607981078249472"
default_url = "https://github.com/Pugie38/Undertale-Yellow-AP/releases/download/v{{version}}/undertale_yellow.apworld"

[versions]
"0.3.0+hotfix2" = { url = "https://github.com/Pugie38/Undertale-Yellow-AP/releases/download/v0.3.0/undertale_yellow.apworld" }
