name = "YARGRockBand2"
display_name = "YARG Rock Band 2"
home = "https://discord.com/channels/731205301247803413/1454538103933898752"
default_url = "https://github.com/GirlWithoutAFairy/YARGArchipelago-GH-and-RB-forks/releases/download/26.05.10/YARGRockBand2.apworld"

[versions]
"26.05.10" = {}
